defaults:
  - _self_
  - hydra: default
  - model: raliflow
  
slurm_id: 00000

wandb_mode: offline # [offline, disabled, online]
wandb_project_name: fusionflow
######################################
dataset_path:  /data/autodl-tmp/DATASET/view_of_delft_PUBLIC/vod_sf_5_mask_v9/
######################################


dataset_name: VOD #Argoverse # 
estimate_sf: radar_and_lidar 
vod_mode: radar_lidar 

output: ${model.name}-${slurm_id}

model_name: FusionFlow 
checkpoint: 
# For continue training
pretrained_weights: 


eval_only: False



# trainer
available_gpus: [0, 1, 2, 3]  
gpus: '0, 1, 2, 3' 

num_workers: 16
sync_bn: true
batch_size: 8  
epochs: 100
gradient_clip_val: 5.0
######################################
my_model_save_path: /data/fjy/
######################################

version: 2025

# optimizer ==> Adam
lr: 2e-6
loss_fn: deflowLoss 

# log settings
seed: 42069
log_every: 10 # steps epochs*dataset_size/batch_size
val_every: 2  # epochs
save_top_model: 1 # top_k model will be saved.

voxel_size: [0.1, 0.1, 6] # X Y Z
point_cloud_range: [0, -25.6, -3, 51.2, 25.6, 3]
variation: 1
num_frames: 2  # max to 5

is_freeze: False
dynamic_mask: False 
